### ISSUE TITLE
Is this method considered a type of detection model?

### ISSUE THREAD

**Issue by Ianpengg** [nubot-nudt/InsMOS#2]
Hello, I want to know if we can use this method as a 3d point cloud detection model 
since it can generate the bounding box .

**Comment by neng-wang** [comment]
Hello, sorry for my late reply. Our proposed method is able to be used as a 3D object model, which is built on top of [CenterPoint.](https://github.com/tianweiy/CenterPoint) But object detection is only an intermediate result of our model, our final goal is to achieve instance-based moving object detection.

**Comment by Ianpengg** [comment]
Thanks for replying, I have another question! Based on your model architecture your training pipeline require the semantic point label and instance label ex:bounding box am I right? Since I have the similar idea before, just curious about this.

**Comment by neng-wang** [comment]
Yes! Our proposed method require semantic point label and bounding box for training. We'll release our bounding box data in SemanticKITTI datasets publicly after our paper gets accepted.

**Comment by neng-wang** [comment]
Yes! Our proposed method require semantic point label and bounding box for training. We'll release our bounding box data of SemanticKITTI publicly after our paper gets accepted.

**Comment by Ianpengg** [comment]
Thanks~ Looking forward to the release of the source code.
