### ISSUE TITLE
What is the file structure of the ’data_path‘

### ISSUE THREAD

**Issue by do1nothing** [nubot-nudt/InsMOS#3]
Hello author,

Thank you for your open-source work. I'm encountering an error while running the inference module script, and it seems to be related to a file issue. I've traced the error to the load_poses() function in the dataloader/utils.py file. Here's the error message I received. Below is my file structure for reference. Could you please take a look and help me identify the problem?

Thank you.
![image](https://github.com/nubot-nudt/InsMOS/assets/48348676/a5432f1f-b7af-4d5d-a51a-74388d6cfdb8)
![image](https://github.com/nubot-nudt/InsMOS/assets/48348676/69366683-13e1-4392-9858-0803b5771e54)

**Comment by neng-wang** [comment]
Sorry for my late reply.
It looks like the wrong file path was typed. You can check the path to the file via the 'print()' function in the line https://github.com/nubot-nudt/InsMOS/blob/20460c8db7479517d3209123a1a78111d1562564/scripts/predict_mos.py#L182

**Comment by neng-wang** [comment]
Actually for moving object segmentation ,we usually choose the poses provided by SemanticKITTI which is being generated through SuMa algorithm. Based on the image you provided, I'm guessing you're using the pose truth provided by KITTI odometry datasets. You can get more detailed information in [SemanticKITTI ](http://semantic-kitti.org/dataset.html) and download the poses in [here](http://[jbehley.github.io/projects/surfel_mapping/index.html].(http://jbehley.github.io/projects/surfel_mapping/index.html)). 
In InsMOS, we choose the poses with loopclosure generated by the SuMa.
