### ISSUE TITLE
about generalization on apollo

### ISSUE THREAD

**Issue by Terminal-K** [nubot-nudt/InsMOS#5]
Hi, thanks for your excellent work!
When I tested the weights both with and without KITTI-Road (provided by [README](https://github.com/nubot-nudt/InsMOS#inference)) directly on the Apollo dataset (provided by [MapMOS](https://github.com/PRBonn/MapMOS?tab=readme-ov-file#publication)), I found that the metrics were very low (mIoU < 0.2). 
Are there any considerations that I should be aware of?

**Comment by neng-wang** [comment]
Hi @Terminal-K, thank you for your attention to our work.

The main reason for this situation is that the reflection intensity in the Apollo dataset provided by MapMOS is significantly different from SemanticKITTI. In fact, I don't know how MapMOS obtains this value. That may not be the reflection intensity. In the Apollo dataset we use, the reflection intensity of LiDAR points is similar to SemanticKITTI. 
For your testing convenience, we provide the reflection intensity we use [[link,code:hs93]](https://pan.baidu.com/s/1my_TMDwaw4OSdo1_93Empg?pwd=hs93), and you can easily modify the function https://github.com/nubot-nudt/InsMOS/blob/b7f9ba5ff3b18a14278090e7c8e551def7d2f6ad/scripts/predict_mos.py#L199  to complete the test.
```
  self.intensity_folder="xx/InsMOS/intensity/sequences"
  def read_point_cloud(self, filename):
        """Load point clouds from .bin file"""
        point_cloud = np.fromfile(filename, dtype=np.float32)
        point_cloud = point_cloud.reshape((-1, 4))

        intensity_file = os.path.join(self.intensity_folder,filename[-22:])
        intensity = np.fromfile(intensity_file, dtype=np.float32).reshape((-1, 1))
        new_point_cloud = np.concatenate((point_cloud[:,:3],intensity),axis=1)
        return new_point_cloud
```

**Comment by Terminal-K** [comment]
Hi, @neng-wang, many thanks for your reply!! 
However, i notice that the link you gave only contains data of velodyne. Is it convenient to provide the other files such as pose or label?

**Comment by neng-wang** [comment]
Hi @Terminal-K!

This link contains only the intensity values of each LiDAR scan, without the x, y, z coordinates. Its data format is Nx1. I assume you have already downloaded the Apollo dataset provided by MapMOS. Therefore, I only provide the intensity values for the sake of convenience in downloading. The other poses and labels are the same as those in MapMOS.

You can directly download this link and simply modify the `read_point_cloud` function mentioned above to replace the intensity values. Then, use InsMOS to complete the generalization test

**Comment by Terminal-K** [comment]
Hi @neng-wang, thanks for your patient reply!!
I forget to check the file carefully because of carelessness, and you are absolutely right!!
Thanks again for your help!

Wish you all the best.
